apiVersion: serving.kserve.io.opendatahub.io/v1beta1
kind: InferenceService
metadata:
  labels:
    app.kubernetes.io/name: connections-api
    app.kubernetes.io/managed-by: kustomize
  name: inferenceservice-sample
spec:
  # TODO(user): Add fields here
